# Generated by Django 3.0.7 on 2020-06-24 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Blocos',
            },
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Numeros',
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencia.Bloco')),
                ('morador', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencia.Numero')),
            ],
            options={
                'verbose_name_plural': 'Residências',
            },
        ),
    ]
