# Generated by Django 3.0.7 on 2020-06-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0002_auto_20200624_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='bloco',
        ),
        migrations.AddField(
            model_name='bloco',
            name='residencias',
            field=models.ManyToManyField(to='residencia.Residencia'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Numero',
        ),
    ]
